version: "3"

services:
  postgres:
    image: postgres:12.4-alpine
    restart: always
    env_file:
      - .env
  
  back-end:
    container_name: back-end
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - 8003:8000
    command: >
      sh -c "python main.py"
    restart: always
    volumes: 
      - ./app:/app
    # Map directories with code for hot reloading